# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 588c71fe50ddf21bcd4b272c0982fdb8cd4ebbcbd50ad9a6d26e855956bf48d399f4e4473d039acc8185e87add3adf0ca55c7ee5e22a729b4a24002c6bdb11bf

test:
  secret_key_base: 11e2fc08071619a8254ee583dbfa2021e5c871278c4d96298e9c048c0718c47951a7718c1ceae9c590694ef2b2ae00ce5209cb0b5a193e848fb5782fd1de08bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
